### ISSUE TITLE
ValueError...

### ISSUE THREAD

**Issue by anxingle** [jorjasso/VLAD#1]
Thanks  a lot for your project. I run your code ,  and compute descriptors, Construct  visual dictionary, compute VLAD descriptors is ok . But when I ran indexBallTree , it shows:  
D:\vlad\>D:\Anaconda2\python.exe  indexBallTree.py  -d VLADdescriptors/VLAD_SIFT_W2.pickle  -l 10 -o ballTreeIndexes/index_SIFT_W2
```python 
indexing VLAD descriptors from VLADdescriptors/VLAD_SIFT_W2.pickle with a ball tree:
Traceback (most recent call last):
  File "indexBallTree.py", line 44, in <module>
    tree = indexBallTree(V,leafSize)
  File "D:\workspace\image_similarity\vlad\siler_vlad\VLAD.py", line 240, in indexBallTree
    tree = BallTree(X, leaf_size=leafSize)
  File "sklearn\neighbors\binary_tree.pxi", line 1055, in sklearn.neighbors.ball_tree.BinaryTree.__init__ (sklearn\neighbors\ball_tree.c:9180)
  File "sklearn\neighbors\binary_tree.pxi", line 217, in sklearn.neighbors.ball_tree.get_memview_DTYPE_2D (sklearn\neighbors\ball_tree.c:3127)
ValueError: Buffer has wrong number of dimensions (expected 2, got 1)
```

**Comment by appleleaves** [comment]
I am facing the same problem! Have you fix it?

**Comment by GhostSen** [comment]
> I am facing the same problem! Have you fix it?
Step  3 maybe be error.You should set right dataset path.Then,you check out of input and output results of every step.
